//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Host.ServiceRef {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceRef.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Insert", ReplyAction="http://tempuri.org/IService1/InsertResponse")]
        int Insert(LiveScoreSystem.WCFContact ContactPar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Insert", ReplyAction="http://tempuri.org/IService1/InsertResponse")]
        System.Threading.Tasks.Task<int> InsertAsync(LiveScoreSystem.WCFContact ContactPar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Update", ReplyAction="http://tempuri.org/IService1/UpdateResponse")]
        int Update(LiveScoreSystem.WCFContact ContactPar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Update", ReplyAction="http://tempuri.org/IService1/UpdateResponse")]
        System.Threading.Tasks.Task<int> UpdateAsync(LiveScoreSystem.WCFContact ContactPar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SelectAll", ReplyAction="http://tempuri.org/IService1/SelectAllResponse")]
        LiveScoreSystem.WCFContact[] SelectAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SelectAll", ReplyAction="http://tempuri.org/IService1/SelectAllResponse")]
        System.Threading.Tasks.Task<LiveScoreSystem.WCFContact[]> SelectAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Delete", ReplyAction="http://tempuri.org/IService1/DeleteResponse")]
        int Delete(LiveScoreSystem.WCFContact ContactPar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Delete", ReplyAction="http://tempuri.org/IService1/DeleteResponse")]
        System.Threading.Tasks.Task<int> DeleteAsync(LiveScoreSystem.WCFContact ContactPar);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : Host.ServiceRef.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<Host.ServiceRef.IService1>, Host.ServiceRef.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int Insert(LiveScoreSystem.WCFContact ContactPar) {
            return base.Channel.Insert(ContactPar);
        }
        
        public System.Threading.Tasks.Task<int> InsertAsync(LiveScoreSystem.WCFContact ContactPar) {
            return base.Channel.InsertAsync(ContactPar);
        }
        
        public int Update(LiveScoreSystem.WCFContact ContactPar) {
            return base.Channel.Update(ContactPar);
        }
        
        public System.Threading.Tasks.Task<int> UpdateAsync(LiveScoreSystem.WCFContact ContactPar) {
            return base.Channel.UpdateAsync(ContactPar);
        }
        
        public LiveScoreSystem.WCFContact[] SelectAll() {
            return base.Channel.SelectAll();
        }
        
        public System.Threading.Tasks.Task<LiveScoreSystem.WCFContact[]> SelectAllAsync() {
            return base.Channel.SelectAllAsync();
        }
        
        public int Delete(LiveScoreSystem.WCFContact ContactPar) {
            return base.Channel.Delete(ContactPar);
        }
        
        public System.Threading.Tasks.Task<int> DeleteAsync(LiveScoreSystem.WCFContact ContactPar) {
            return base.Channel.DeleteAsync(ContactPar);
        }
    }
}
