//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiveScoreClient.ServiceRef {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceRef.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/insertTeams", ReplyAction="http://tempuri.org/IService1/insertTeamsResponse")]
        void insertTeams(LiveScoreSystem.WCFContact teams);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/insertTeams", ReplyAction="http://tempuri.org/IService1/insertTeamsResponse")]
        System.Threading.Tasks.Task insertTeamsAsync(LiveScoreSystem.WCFContact teams);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : LiveScoreClient.ServiceRef.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<LiveScoreClient.ServiceRef.IService1>, LiveScoreClient.ServiceRef.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void insertTeams(LiveScoreSystem.WCFContact teams) {
            base.Channel.insertTeams(teams);
        }
        
        public System.Threading.Tasks.Task insertTeamsAsync(LiveScoreSystem.WCFContact teams) {
            return base.Channel.insertTeamsAsync(teams);
        }
    }
}
